### PR TITLE
Bot user check

### PR DESCRIPTION
**Pull request by melihmutlu**
I implemented GET and POST methods to get and add TelegramUser
Telegram bot also checks if user exists when it gets new message. If user does not exist, bot creates a new TelegramUser in database.

### CODE REVIEW

**Comment by melihmutlu** [comment]
Telegram Bot sends request to a local link for now since we don't have a public URL yet.

**Comment by agoz17** [comment]
Very useful contributions. Looks like bug free.

**Comment by sevgicansalih** [comment]
It looks like you need to do makemigrations in order to merge without conflicts

**Comment by sevgicansalih** [comment]
You should do makemigrations in order to merge without conflict

**Pull request merged**
