### PR TITLE
Wit train by templates from database feature added

### PR DESCRIPTION
**Pull request by tahakucukkatirci**
I am committing the modified witapi.py file. The methods to perform the training by database templates added.

### CODE REVIEW

**Review by theTytoAlba — APPROVED** [review]
Hi! Thank you for the training functionality, this is going to help us A LOT. :)

One little comment: I see that there are a lot of unnecessary empty lines around. Can you please trim them? (See lines 8, 9, 57, 59, 71, 73, 87, 89, 98, 100, 108). Also there are more than enough tabs in some lines: lines 77 to 84 have 8 tabs for example, maybe align them with the "'text':template" in the append function?

You can get rid of the conflict by removing the DS files. Then we can merge. :)

**Comment by theTytoAlba** [comment]
Thanks! This looks good. Once you fix the conflict, we can merge this. :)

Here is an easy way to fix conflict:
git checkout -- filename
This should revert the changes you made to the specified file, in this case, .DS_Store.

Hope it helps. :)

**Comment by tahakucukkatirci** [comment]
Hi, 

I resolved the conflicts. It is now ready to be merged. Thanks for the warning. It also made me realize some minor bugs in the code. I fixed them and then committed witapi.py again.

**Comment by theTytoAlba** [comment]
Merging, thanks!

**Pull request merged**
