### PR TITLE
Created template logic

### PR DESCRIPTION
**Pull request by theTytoAlba**
Hi!
This pull request implements the template model.
I did some research and found out that it is quite tricky to have a list of strings as a field to a model. So I have created a new model for templates.
Currently, a template is made of a string which is the sentence that will imply an intent, and a node which the template belongs to.
These two are 'must have's.
User can filter the templates by nodes using the bar on the right of the admin panel, so it is rather easy to use.
We will later use the <template.template, template.node.intent> pairs to train wit.ai.

Please take a look!

screen shot 2017-10-23 at 15 16 46

### CODE REVIEW

**Comment by agoz17** [comment]
We need to consider these lines of the models.py file.
-    created = models.DateTimeField(default=timezone.now)
 +    created = models.DateTimeField(auto_now_add=True)

The first line is needed for the code I 've written for http request. Since they have same functionality I suggest that it stays.

Other than that TelegramUser model is not here in models.py, is this because we couldn't merge it before implementing it? You are very fast Irmak, congrutulations :D

**Comment by agoz17** [comment]
1-created = models.DateTimeField(default=timezone.now)
2-created = models.DateTimeField(auto_now_add=True) 
We don't need to code in line 1. I found out the problem with the line 2. It was specific to my system, so I have no problem with line 2.

**Comment by theTytoAlba** [comment]
Hi!
I have been dealing with merge conflicts and I think all is fine now. Is it okay if I merge it with  models.DateTimeField(auto_now_add=True) ?
This one automatically adds current date to created field while the other one expects user to pick a date for every object. I think this way it is better. Does it block anything on your side?

**Comment by agoz17** [comment]
I think everything is perfect. It doesn't block anything on my side. I am merging this branch.

**Pull request merged**
